parameters:
    tables.sitemaker.blocks: '%core.table_prefix%sm_blocks'
    tables.sitemaker.block_routes: '%core.table_prefix%sm_block_routes'
    tables.sitemaker.cblocks: '%core.table_prefix%sm_cblocks'
    tables.sitemaker.menus: '%core.table_prefix%sm_menus'
    tables.sitemaker.menu_items: '%core.table_prefix%sm_menu_items'
