steve_postreactions_add_reaction_controller:
    path: /add_reaction/{post_id}/{type_id}
    defaults: { _controller: steve.postreactions.add_reaction:add }
    requirements:
        type_id: \d+

steve_postreactions_delete_reaction_controller:
    path: /delete_reaction/{post_id}/{user_id}
    defaults: { _controller: steve.postreactions.delete_reaction:delete }
    requirements:
        user_id: \d+
        
steve_postreactions_resync_reaction_controller:
    path: /resync_reaction/{post_id}/{user_id}
    defaults: { _controller: steve.postreactions.resync_reaction:resync }
    requirements:
        user_id: \d+
        
steve_postreactions_view_reactions_controller_page:
    path: /reactions
    defaults: { _controller: steve.postreactions.controller_page:view_reactions }

steve_postreactions_view_reactions_controller_pages:
    path: /reaction/{post_id}
    defaults: { _controller: steve.postreactions.controller_page:post_reactions }
    requirements:
        post_id: \d+
