imports:
    - { resource: tables.yml }

services:
    # controllers
    steve.postreactions.acp_controller:
        class: steve\postreactions\controller\acp_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@notification_manager'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '@steve.postreactions.delete_reactions'            
            - '@steve.postreactions.reaction_types'
            - '%steve.postreactions.tables.reactions_table%'
            - '%steve.postreactions.tables.reaction_types_table%'
            
    steve.postreactions.ucp_controller:
        class: steve\postreactions\controller\ucp_controller
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@steve.postreactions.reaction_types'
            
    steve.postreactions.add_reaction:
        class: steve\postreactions\controller\add_reaction
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@notification_manager'
            - '@request'
            - '@user'
            - '@steve.postreactions.reaction_types'
            - '%steve.postreactions.tables.reactions_table%'

    steve.postreactions.delete_reaction:
        class: steve\postreactions\controller\delete_reaction
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@notification_manager'
            - '@request'
            - '@user'
            - '@steve.postreactions.reaction_types'
            - '%steve.postreactions.tables.reactions_table%'

    steve.postreactions.controller_page:
        class: steve\postreactions\controller\reaction_pages
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@pagination'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '@steve.postreactions.reaction_types'           
            - '%steve.postreactions.tables.reactions_table%'
            
    steve.postreactions.resync_reaction:
        class: steve\postreactions\controller\resync_reactions
        arguments:
            - '@auth'
            - '@config'            
            - '@dbal.conn'         
            - '@request'
            - '@user'
            - '%core.php_ext%'
            - '%core.root_path%'         
            - '%steve.postreactions.tables.reactions_table%'
            
    #operators
    steve.postreactions.delete_reactions:
        class: steve\postreactions\reaction\delete_reactions
        arguments:
            - '@dbal.conn'
            - '@notification_manager'
            - '@steve.postreactions.reaction_types'
            - '%steve.postreactions.tables.reactions_table%'

    steve.postreactions.reaction_types:
        class: steve\postreactions\reaction\reaction_types
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'           
            - '@controller.helper'
            - '@template'
            - '@path_helper'
            - '%steve.postreactions.tables.reactions_table%'
            - '%steve.postreactions.tables.reaction_types_table%'
            
    steve.postreactions.user_reactions:
        class: steve\postreactions\reaction\user_reactions
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '@steve.postreactions.reaction_types'           
            - '%steve.postreactions.tables.reactions_table%'
            
    #listeners       
    steve.postreactions.acp_listener:
        class: steve\postreactions\event\acp_listener
        arguments:
            - '@dispatcher'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }

    steve.postreactions.general_listener:
        class: steve\postreactions\event\general_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@dispatcher'
            - '@language'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
            
    steve.postreactions.posting_listener:
        class: steve\postreactions\event\posting_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@steve.postreactions.delete_reactions'
            - '@steve.postreactions.reaction_types'
            - '%steve.postreactions.tables.reactions_table%'
        tags:
            - { name: event.listener }

    steve.postreactions.user_listener:
        class: steve\postreactions\event\user_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'            
            - '@dispatcher'
            - '@user'
            - '@steve.postreactions.delete_reactions'
            - '@steve.postreactions.user_reactions'
            - '%steve.postreactions.tables.reactions_table%'
        tags:
            - { name: event.listener }   
   
    steve.postreactions.viewtopic_listener:
        class: steve\postreactions\event\viewtopic_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@dispatcher'
            - '@template_context'
            - '@template'
            - '@user'
            - '@steve.postreactions.reaction_types'
            - '%steve.postreactions.tables.reactions_table%'
        tags:
            - { name: event.listener }
            
    #notifications
    steve.postreactions.notification.type.reaction:
        class: steve\postreactions\notification\type\reaction
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_config, ['@config']]
            - [set_user_loader, ['@user_loader']]
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
