services:
    rmcgirr83.applicationform.main.controller:
        class: rmcgirr83\applicationform\controller\main_controller
        arguments:
            - '@auth'		
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@rmcgirr83.applicationform.applicationform'
            - '@captcha.factory'			
            - '@?rmcgirr83.topicdescription.listener'
    rmcgirr83.applicationform.listener:
        class: rmcgirr83\applicationform\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@rmcgirr83.applicationform.applicationform'
        tags:
            - { name: event.listener }
    rmcgirr83.applicationform.applicationform:
        class: rmcgirr83\applicationform\core\applicationform
        arguments:
            - '@dbal.conn'
            - '@user'
