services:
    phpbb.mediaembed.listener:
        class: phpbb\mediaembed\event\main_listener
        arguments:
            - '@config'
            - '@config_text'
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
