services:
    pcgf.pmnamesuggestions.listener:
        class: pcgf\pmnamesuggestions\event\listener
        arguments:
            - '@template'
            - '@controller.helper'
            - '@config'
        tags:
            - { name: event.listener }
    pcgf.pmnamesuggestions.controller:
        class: pcgf\pmnamesuggestions\controller\controller
        arguments:
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@config'
            - '%core.root_path%'